import {Injectable} from '@angular/core';
import {Subject} from "rxjs/Subject";
@Injectable()
export class Dataservice {
  cart: Subject<any>;
  constructor() {
    this.cart = new Subject<any>();
    }
    getFortuneCookies() {
      const cookies = [
        "There is a true and sincere friendship between you and your friends",
        "A stranger will cross your path who later becomes your friend",
        "You find beauty in ordinary things, do not lose this ability",
        "An old acquaintance will re-enter your life",
        "Ideas are like children; there are none so wonderful as your own",
        "A chance happening will reveal your destiny",
        "It takes more than good memory to have good memories",
        "A wise person will give you timely advice",
        "A thrilling time is in your immediate future",
        "Love will be found from a past meeting",
        "Your blessing is no more than being safe and sound for the whole lifetime",
        "Kind words may mean more than they seem",
        "Plan for many pleasures ahead",
        "A new friendship will bring unexpected joy",
        "The joyfulness of a man prolongeth his days",
        "Your future will be happy and productive",
        "Your everlasting patience will be rewarded sooner or later",
        "Recognition will come from unexpected sources",
        "Make two grins grow where there was only a grouch before",
        "If you're not sure where you're going, you'll probably end up somewhere else.",
        "Something you lost will soon turn up",
        "Some make it happen, some watch it happen, and some say, 'What happened?'",
        "Your heart is pure, and your mind clear, and your soul devout",
        "Failure is a dress rehearsal for success",
        "Excitement and intrigue follow you closely wherever you go!",
        "If our thoughts and hopes are elsewhere, it is impossible to set our faces steadily toward the work required of us.",
        "A pleasant surprise is in store for you",
        "Your dreams are an index to your greatness",
        "May life throw you a pleasant curve",
        "Be not afraid of growing slowly, be afraid only of standing still",
        "As the purse is emptied the heart is filled",
        "What you see depends mainly on what you look for",
        "Be mischievous and you will not be lonesome",
        "No dreamer is ever too small; no dream is ever too big",
        "You have a deep appreciation of the arts and music",
        "Do not give up, the beginning is always the hardest",
        "Your flair for the creative takes an important place in your life",
        "You are never given a wish without also being given the power to make it true. You may have to work for it, however. ",
        "Your artistic talents win the approval and applause of others",
        "Your smile brings happiness to everyone you meet",
        "Pray for what you want, but work for the things you need",
        "A smooth sea never made a skillful mariner!",
        "Your many hidden talents will become obvious to those around you",
        "And in the end it's not the years in your life that count. It's the life in your years.",
        "Don't forget, you are always on our minds",
        "If you think you can, you can",
        "Your greatest fortune is the large number of friends you have",
        "It matters not what road we take but rather what we become on the journey",
        "A firm friendship will prove the foundation on your success in life",
        "The only man who never makes mistakes is the man who never does anything",
        "Don't ask, don't say. Everything lies in silence",
        "If you want the rainbow, you have to tolerate the rain",
        "Look for new outlets for your own creative abilities",
        "Good timber does not grow with ease; the stronger the wind, the stronger the trees",
        "Be prepared to accept a wondrous opportunity in the days ahead!",
        "A ship in harbor is safe, but that's not why ships are built",
        "Fame, riches and romance are yours for the asking",
        "Whatever you want to do, do it. There are only so many tomorrows.",
        "Good luck is the result of good planning",
        "You thrive on adventure, try something new",
        "Good things are being said about you",
        "To think is easy; to act is difficult. To act as one thinks is the most difficult of all.",
        "Smiling often can make you look and feel younger",
        "If you wish to see the best in others, show the best of yourself",
        "Someone is speaking well of you",
        "Whenever possible, keep it simple",
        "The time is right to make new friends",
        "You should let go of negative things today",
        "You will inherit some money or a small piece of land",
        "Winning starts with beginning",
        "Your life will be happy and peaceful",
        "You are ready to take on the world",
        "A friend is a present you give yourself",
        "When one must, one can",
        "A member of your family will soon do something that will make you proud",
        "We can't control the wind, be we can always adjust the sails",
        "A quiet evening with friends is the best tonic for a long day",
        "Men do not fail... they give up trying",
        "A single kind word will keep one warm for years",
        "A single conversation with a wise man is better than ten years of study",
        "Anger begins with folly, and ends with regret",
        "A pleasant experience is ahead: don’t pass it by",
        "Generosity and perfection are your everlasting goals",
        "A beautiful, smart, and loving person will be coming into your life",
        "Happy news is on its way to you",
        "A great pleasure in life is doing what others say you can't",
        "He who laughs at himself never runs out of things to laugh at",
        "A feeling is an idea with roots",
        "If your desires are not extravagant they will be granted",
        "A single kind work will keep one warm for years",
        "Let there be magic in your smile and firmness in your handshake",
        "Before you can be reborn you must die",
        "If you want the rainbow, you must put up with the rain",
        "Count your blessings by thinking of those who love you",
        "Nature, time and patience are the three best physicians",
        "We cannot do great things; only small things with great love",
        "Strong and bitter words indicate a weak cause.",
        "A secret admirer is now plotting how to win your heart",
        "The beginning of wisdom is to desire it",
        "Bread today is better than cake tomorrow",
        "You will have a very pleasant experience",
        "Be direct, usually one can accomplish more that way",
        "You will inherit some money or a small piece of land",
        "Back away from individuals who are impulsive",
        "You will live a long, happy life",
        "All progress occurs because people dare to be different",
        "You will spend old age in comfort and material wealth",
        "Aim high, time flies",
        "You will step on the soil of many countries",
        "Be patient! The Great Wall didn’t got build in one day.",
        "You will take a chance in something in the near future",
        "There will come a time when you wish you'd given love a chance",
        "You will witness a special ceremony",
        "Your dearest wish will come true",
        "Your everlasting patience will be rewarded sooner or later",
        "You think it's a secret, but they know",
        "Your great attention to detail is both a blessing and a curse",
        "He who laughs at himself never runs out of things to laugh at",
        "Your heart is a place to draw true happiness",
        "A conclusion is simply the place where you got tired of thinking",
        "Your ability to juggle many tasks will take you far",
        "A closed mouth gathers no feet",
        "A friend asks only for your time, not your money",
        "The fortune you seek is in another cookie",
        "You will be invited to an exciting event",
        "Your dream will come true when you least expect it",
        "Do not be covered in sadness or be fooled in happiness; they both must exist",
        "Stop letting other people stand in your way",
        "If you wish to know the mind of a man, listen to his words",
        "Make a wise choice everyday",
        "Never underestimate the power of the human touch",
        "Rivers need springs",
        "The cure for grief is motion",
        "The best is yet to come",
        "Stop searching forever, happiness is just next to you",
        "Someday everything will all make perfect sense",
        "Seize every second of your life and savor it",
        "Poverty is no disgrace",
        "Vision is the art of seeing what is invisible to others",
        "Unleash your life force",
        "Two small jumps are sometimes better than one big leap",
        "True wisdom is found in happiness",
        "Today is an ideal time to water your personal garden",
        "Those who walk in other's tracks leave no footprints",
        "Think you can. Think you can't. Either way, you'll be right",
        "Things are never quite the way they seem",
        "There is someone rather annoying in your life that you need to listen to",
        "The Wheel of Good Fortune is finally turning in your direction!",
        "The object of your desire comes closer",
        "The harder you try to not be like your parents, the more likely you will become them",
        "The man who waits till tomorrow, misses the opportunities of today",
        "You will soon be honored by someone you respect",
        "You will soon discover a major truth about the one you love most",
        "You will soon witness a miracle",
        "you will think for yourself when you stop letting others think for you",
        "You will plant the smallest seed and it will become the greatest and most mighty tree in the world",
        "You will be rewarded for being a good listener in the next week",
        "A focused mind is one of the most powerful forces in the universe",
        "A dream you have will come true",
        "A clear conscience is usually the sign of a bad memory",
        "A big fortune will descend upon you this year",
        "A merry heart does good like a medicine",
        "A new business venture is on the horizon",
        "Discover the power within yourself",
        "Do not fear what you don't know",
        "Do not follow where the path may lead. Go where there is no path...and leave a trail",
        "Conquer your fears or they will conquer you",
        "Good things take time",
        "Good news from afar may bring you a welcome visitor",
        "Generosity will repay itself sooner than you imagine",
        "Find a peaceful place where you can make plans for the future",
        "For success today look first to yourself",
        "Friendship is an ocean that you cannot see bottom",
        "Expect great things and great things will come",
        "Do not worry, you will have great peace",
        "Do what is right, not what you should",
        "Do what you want, when you want, and you will be rewarded",
        "It is never too late. Just as it is never too early",
        "Trust your friends, but keep your eyes open",
        "Tomorrow is another day",
        "Pay attention to your family. Don't take them for granted.",
        "An exciting adventure awaits you",
        "Show everyone what you can do",
        "Happiness may be right under your nose",
        "Lead by example, not by words alone",
        "It may be difficult, but it will be worth it in the end",
        "Work first, but make sure to play later",
        "Don't hesitate to tackle a difficult problem",
        "You will soon receive a surprise from a lover",
        "True happiness makes us wise",
        "Seek out a new environment if you're stuck in a rut",
        "Free your mind, and the rest will follow",
        "Do your job to the best of your ability",
        "Trust your friends, but keep your eyes open",
        "Get ready for a life-changing event!",
        "Respect your elders. You could inherit a large sum of money.",
        "Don't wait for success to come - go find it!",
        "Go with your gut feeling",
        "You excel at pleasing others"
      ];
      return cookies;
    }
}
